/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package games.poker;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int poker=0x7f050000;
        public static final int text=0x7f050001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int ace=0x7f040000;
        public static final int app_name=0x7f040016;
        public static final int card=0x7f040014;
        public static final int club=0x7f04000e;
        public static final int diamond=0x7f04000d;
        public static final int draw=0x7f040024;
        public static final int drop=0x7f040013;
        public static final int eight=0x7f040007;
        public static final int five=0x7f040004;
        public static final int five_kind=0x7f040021;
        public static final int flush=0x7f04001c;
        public static final int four=0x7f040003;
        public static final int four_kind=0x7f04001e;
        public static final int full_house=0x7f04001d;
        public static final int game_paused=0x7f040025;
        public static final int heart=0x7f04000f;
        public static final int high_card=0x7f040017;
        public static final int hold=0x7f040011;
        public static final int jack=0x7f04000a;
        public static final int king=0x7f04000c;
        public static final int lose=0x7f040023;
        public static final int nine=0x7f040008;
        public static final int pair=0x7f040018;
        public static final int play=0x7f040012;
        public static final int queen=0x7f04000b;
        public static final int royal_flush=0x7f040020;
        public static final int seven=0x7f040006;
        public static final int six=0x7f040005;
        public static final int spade=0x7f040010;
        public static final int straight=0x7f04001b;
        public static final int straight_flush=0x7f04001f;
        public static final int ten=0x7f040009;
        public static final int three=0x7f040002;
        public static final int three_kind=0x7f04001a;
        public static final int two=0x7f040001;
        public static final int two_pair=0x7f040019;
        public static final int unknown=0x7f040015;
        public static final int win=0x7f040022;
    }
}
